### ISSUE TITLE
Graph features

### ISSUE THREAD

**Issue by zsun227** [declare-lab/kingdom#1]
Hello, thanks a lot for sharing your code!

I'm not very sure how to get the graph features in the folder "graph_features"
I wonder if you could provide the code to train/extract graph features from the Commonsense Graph?

Thanks!

**Comment by deepanwayx** [comment]
We will add the code for graph pre-training and feature extraction soon. Please look out for future updates.

**Comment by deepanwayx** [comment]
Added in the latest commit.
